#! /bin/sh

# Set your wallpaper
feh --bg-fill $HOME/Pictures/Wallpapers/wp2.png &

# Run picom compositor
. "${HOME}/.config/picom/launch.sh" &

# Launch polybar
. "${HOME}/.config/polybar/launch.sh" &

# Launch sxhkd
. "${HOME}/.config/sxhkd/launch.sh" & 

# Set the border colors for focused, active and inactive windows
bspc config normal_border_color "#282828"
bspc config active_border_color "#928374"
bspc config focused_border_color "#ebdbb2"

bspc config presel_feedback_color "#282828"

# Focus the window the mouse is on
bspc config focus_follows_pointer true

# Define window settings
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
